# Setting a New prefix for tmux
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split using using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %


# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
bind-key -n S-Left swap-window -t -1
bind-key -n S-Right swap-window -t +1
bind-key n new-window
bind-key -r C-Right next-window
bind-key -r C-Left previous-window
bind-key -r o last-window
bind -r C-h resize-pane -L 3
bind-key r command-prompt -I "#W" "rename-window '%%'"
bind -r C-j resize-pane -D 3
bind -r C-k resize-pane -U 3
bind -r C-l resize-pane -R 3

# Enable Mouse Mode
set -g mouse on

# Source File Keybind
bind R source-file ~/.tmux.conf \; display-message "Config reloaded.."

# Stop renaming of windows
set-option -g allow-rename off
set-window-option -g automatic-rename off
set -g @continuum-restore 'on'

# Install Plugins (Prefix+ I to install plugins)
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'
set -s default-terminal 'tmux-256color'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# status

# messages
set -g message-style fg="${thm_cyan}",bg="${thm_gray}",align="centre"
set -g message-command-style fg="${thm_cyan}",bg="${thm_gray}",align="centre"

# panes
set -g pane-border-style fg="${thm_gray}"
set -g pane-active-border-style fg="${thm_blue}"

setw -g clock-mode-colour "${thm_blue}"
setw -g mode-style "fg=${thm_pink} bg=${thm_black4} bold"


# Tmux Plugin Manager
set-option -g @plugin 'b0o/tmux-autoreload'
set-option -g pane-border-style "fg=#1a1a1a,bg=#1a1a1a"
set-option -g pane-active-border-style "fg=#1a1a1a,bg=#1a1a1a"

# Dracula Setting
set -g @dracula-plugins "battery weather time"
set -g @dracula-show-powerline true
set -g @dracula-show-fahrenheit false
set -g @dracula-military-time true

run '~/.tmux/plugins/tpm/tpm'